name: Infrastructure destroy pipeline
on: [workflow_dispatch]
jobs:
  DEV: 
    runs-on: X64
    steps: 
      - name: Destroying the Infrastructure
        uses:  actions/checkout@v4 
        run: | 
          cd tools-infra ;cd terraform 
          terraform destroy -auto-approve