name: Infrastructure destroy pipeline
on: 
  workflow_dispatch:
jobs:
  DEV: 
    runs-on: X64
    steps: 
      - name: Destroying the Infrastructure
        run: |
          ls -la 
          cd tools-infra ; cd  terraform ; terraform destroy -auto-approve

        