name: Infrastructure destroy pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64    
    steps:
      - name: Import secrets hashicorp 
        uses: hashicorp/vault-action@v2.4.0
        with: 
          url: ${{secrets.VAULT_SERVER}}
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true  #add to runner later /usr/local/share/ca-certificates/vault-ca.crt
          secrets: | 
            tools/data/aws aws_user | AWS_USER;   
            tools/data/aws aws_password |AWS_PASSWORD
         #   # tools/data/aws vault_token |VAULT_TOKEN
        # tools is secretengine-check api 
      - uses: actions/checkout@v4
      - name: Destroying infra Please wait
      # export TF_VAR_vault_token=${{secrets.VAULT_TOKEN}}
        run: |
            BASE_DIR="/actions-runner/_work/learn-devops-project-infra/learn-devops-project-infra"
            echo "Destroying infrastructure "
            cd "$BASE_DIR/tools-infra/terraform"      # Always reset to the correct directory
            pwd
            ls -la 
            terraform init;terraform destroy -auto-approve
            cd - > /dev/null                       # Move back to the original working directory
        
        env: 
          TF_VAR_aws_password: ${{env.aws_password}}
          TF_VAR_aws_user: ${{env.aws_user}}