name: Infrastructure provisioning pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64    
    steps: 
      - uses: actions/checkout@v4
      - run: echo test
        name: run terraform 
      - run: |
          ls -la
          cd tools-infra; cd terraform
          ls -la
          terraform init  ; terraform apply -auto-approve
      - name: Import secrets hashicorp 
        uses: hashicorp/vault-action@v2.4.0
        with: 
          url: ${{secrets.VAULT_SERVER}}
          token: ${{secrets.VAULT_TOKEN}}
          secrets: | 
            secret/data/tools/aws aws_user | AWS_USER;
      - name: AWS user 
        run:  echo "${{env.AWS_USER}}"
     