name: Infrastructure provisioning pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64    
    steps: 
      - uses: actions/checkout@v4
        with: 
          sparse-chekout: |
            ansible
            terraform
      - run: echo test
        name: run terraform 
      - run: |
          ls -la
          cd terraform
          ls -la
          terraform init  
     