name: Infrastructure provisioning pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64
    steps: 
      - run: echo test
        name: run terraform 
      - run: |
          ls -la
          cd ..
          ls -la
          terraform init  
     