name: Infrastructure provisioning pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64    
    steps:
      - name: Import secrets hashicorp 
        uses: hashicorp/vault-action@v2.4.0
        with: 
          url: ${{secrets.VAULT_SERVER}}
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true  #add to runner later /usr/local/share/ca-certificates/vault-ca.crt
          secrets: | 
            tools/data/aws aws_user | AWS_USER;   
            tools/data/aws aws_password |AWS_PASSWORD
        # tools is secretengine-check api 
      - uses: actions/checkout@v4
      - run: echo test
        name: run terraform 
      - run: |
          ls -la
          cd tools-infra; cd terraform
          ls -la
          terraform init  ; terraform apply -auto-approve
      
      - name: AWS user 
        run:  echo "${{env.AWS_USER}}" ; ls -la
      - name: run shell script 
        run:  |
            ./tools-infra/terraform/infra/userdata.sh

     