name: Infrastructure provisioning pipeline 
on: 
  workflow_dispatch:
jobs: 
  DEV: 
    runs-on: X64    
    steps: 
      - uses: actions/checkout@v4
      - run: echo test
        name: run terraform 
      - run: |
          ls -la
          cd tools-infra; cd terraform
          ls -la
          terraform init  ; teraform apply -auto-approve
     